### ISSUE TITLE
D11 several issues

### ISSUE THREAD

**Issue by danielwerg** [MultiMote/niimblue#42] opened 2024-11-04 00:58 UTC
* Transport:
- [x] Bluetooth (on android phone)
- [ ] Serial (USB)

* Browser console logs (press F12 and copy "Console" tab contents):

Using brave adroid

* Label JSON: *export your label to JSON and attach it here*

```json
[{"width":40,"height":12,"unit":"mm","dpmm":8,"printDirection":"left","title":"D11"}]
```

*describe your issue here*

Default suggested print task (`D11_v1`) was offsetting my labels, after reading https://github.com/MultiMote/niimblue/issues/25 and switching to `D110` offsetting issue was solved

"Snow" always appears no matter the `threshold`

Top 2 were both printed using D110 print task first using min threshold and second using max. The rest of the labels were printed with suggested D11_v1:

![labels](https://github.com/user-attachments/assets/813738a6-806a-4bfe-98ac-fcdd3def0af5)

**Comment by MultiMote** [comment] 2024-11-04 07:23
It's so strange. Can you attach full exported label JSON (you exported just dimensions)? 
Also paste your printer's parameters please (it's unter the "gear" button near the printer's name).

**Comment by danielwerg** [comment] 2024-11-04 07:40
[label_1730705859.json](https://github.com/user-attachments/files/17615119/label_1730705859.json)


```
Printer info:
connectResult: 2
protocolVersion: 1
modelId: 512
serial: [REDACTED]
mac: [REDACTED]
charge: 2
autoShutdownTime: 4
labelType: 1
hardwareVersion: 0x0906
softwareVersion: 0x0903
Model metadata:
model: D11
id: 512
dpi: 203
printDirection: left
printheadPixels: 96
paperTypes: 1,5
densityMin: 1
densityMax: 3
densityDefault: 2
Rfid info:
tagPresent: true
uuid: [REDACTED]
barCode: 01222281
serialNumber: [REDACTED]
allPaper: 192
usedPaper: 49
consumablesType: 1
Heartbeat data:
paperState: -1
rfidReadState: -1
lidClosed: true
powerLevel: 2
```

Also what does `barCode` field represents?

**Comment by MultiMote** [comment] 2024-11-04 07:54
> Also what does `barCode` field represents?

That's some label identifier. It sent to the cloud server from official apps to get label size and some other label parameters.

Example:

  ```http
  POST https://print.niimbot.com/api/template/getCloudTemplateByOneCode HTTP/1.1
  Content-Type: application/json
  niimbot-user-agent: AppVersionName/999.0.0
  
  { "oneCode" : "LABEL_BARCODE" }
  ```

**Comment by MultiMote** [comment] 2024-11-04 09:25
I have no Idea what can cause such behavior.
- That "Snow" not appeared in the print preview dialog? Printer should print exact same image as in preview.
- Try to lower your label dimensions (30x11 for example). Something changed?
- Try to make Bluetooth HCI dump of the print with official NIIMBOT app. That would help a lot.

**Comment by danielwerg** [comment] 2024-11-04 10:36
1. "Snow" in preview doesn't match "snow" in actual print. Even when threshold set to `1` there is still "snow"
2. Same thing
3. Can't find it in the app

---

After resolving #43 I printed label in desktop with default settings and only change `Print task` to D110 — no more snow :D
I wonder why it only happens on phone

**Comment by danielwerg** [comment] 2024-11-04 10:43
Okay, tried on different phone with Chrome and it printed fine as well :/
So it's only my phone, didn't have this issue with niimbot app before it was locked behind account creating.
Maybe an issue with brave mobile? I only installed it because I didn't had chromium browser on phone.

**Comment by danielwerg** [comment] 2024-11-04 10:47
![](https://github.com/user-attachments/assets/30d5babf-609f-48fd-8f53-2dc1082263d4)

**Comment by MultiMote** [comment] 2024-11-04 14:13
> Maybe an issue with brave mobile

Installed latest Brave and still no artifacts.
Personally I am using [Kiwi Browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser) because it have DevTools and has support of Chrome extensions.

**Comment by MultiMote** [comment] 2024-11-05 18:19
I am closing it for now as I didn't found a way to replicate this issue.
Let me know if you can reproduce this on another device.

**Closed by MultiMote** 2024-11-05 18:19 UTC
Labels: bug

**Comment by danielwerg** [comment] 2024-11-06 03:02
@MultiMote what about `Print Task`? It was very unintuitively to use. Only realized I had to use one with different printer name after reading https://github.com/MultiMote/niimblue/issues/25

**Comment by MultiMote** [comment] 2024-11-06 04:41
@danielwerg D11 (modelId 512) has different revisions. Each revision uses different print task. Unfortunately I not fully understand what print task to choose.

Maybe I will figure it out later.

**Comment by MultiMote** [comment] 2024-11-06 08:10
Fixed in https://github.com/MultiMote/niimbluelib/commit/c543bf3ceb1ba24a58d4693aebe15367f801c96d hopefully.

**Comment by MultiMote** [comment] 2025-08-11 08:55
"Snow" issue solution: https://github.com/MultiMote/niimblue/issues/80#issuecomment-2855653540

**Comment by danielwerg** [comment] 2025-08-11 09:18
Thanks for update me on this!
