### ISSUE TITLE
Printhead stuck while testing B1

### ISSUE THREAD

**Issue by d4n1b** [MultiMote/niimblue#6] opened 2024-08-20 14:33 UTC
Hi,

Thanks for the hard work on this!

While testing the website: https://dev.mmote.ru/niimblue/ with my B1 I saw an error with the printhead getting stuck for a while. This is the last moment before releasing the paper:

https://github.com/user-attachments/assets/1d2a9722-a49f-447b-83fb-cc5e06675db2

I have:
- paired the bluetooth with the device using the browser
- paper 50x30mm, matching the config in the UI
- this is my final screen preview before printing:
![image](https://github.com/user-attachments/assets/fa6f6391-f8ea-4bba-ae69-0d78daa3cbc8)

Is this something that has happened to you?

Thanks again! 🙏

**Comment by MultiMote** [comment] 2024-08-20 17:25
Wow, very interesting behavior 😳
I have the same paper and it prints without problems.

https://github.com/user-attachments/assets/ac8aa65d-7d36-4cf7-970c-8b4736cb320a

What kind of transport are you using (bluetooth/serial)?
Please make an export of your canvas and browser logs (F12, console tab).
![image](https://github.com/user-attachments/assets/0d52b64e-81fb-4926-b28a-052fec377911)

**Comment by d4n1b** [comment] 2024-08-20 22:06
Hi! - thanks for the quick reply

This is the info you requested:
- Canvas export: [canvas.json](https://github.com/user-attachments/files/16682786/canvas.json)
- Logs:  [dev.mmote.ru-1724191329654.log](https://github.com/user-attachments/files/16682788/dev.mmote.ru-1724191329654.log)

I also recorded another video and luckily the issue was consistent - perhaps it's something silly I'm doing:

https://github.com/user-attachments/assets/288dda5a-ce31-49ec-9635-648f7646d5e6



Let me know if you need more info or help.

Thanks again! 🙏

**Comment by MultiMote** [comment] 2024-08-21 04:47
Unfortunately, I can't reproduce this issue. I printed both of your labels without problems. What your printer hardware and software versions (you can see it in the Niimbot app)?

> Error: Timeout waiting response (waited for e4)

This error happens when printer processing data too slow (>10s at the moment). Or something bad happened when image transferred to the printer (corrupted packets).

I increased delay between packets (maybe it relates to https://github.com/MultiMote/niimblue/issues/5), try again please (refresh a page firstly).
Can you also try the serial communication if it possible (printer must be powered on before connecting the cable)?

**Comment by d4n1b** [comment] 2024-08-21 07:01
This seems to work fine now:

- Canvas export: [canvas-3.json](https://github.com/user-attachments/files/16687124/canvas-3.json) 
- Logs: [dev.mmote.ru-1724222379215-3.log](https://github.com/user-attachments/files/16687126/dev.mmote.ru-1724222379215-3.log)
- Hardware & software version - are these the same version that you have?
![WhatsApp Image 2024-08-21 at 07 31 26](https://github.com/user-attachments/assets/ea28a073-6a1b-48eb-bf40-250ebda96323)

These are the details from your web app:
```
Model metadata:
{
 "model": "B1",
 "id": [
  4096
 ],
 "dpi": 203,
 "printDirection": "top",
 "printheadPixels": 384,
 "paperTypes": [
  1,
  2,
  5
 ]
}
Printer info:
{
 "connectResult": 3,
 "protocolVersion": 3,
 "model_id": 4096,
 "serial": "****",
 "mac": "****",
 "charge": 3,
 "autoShutdownTime": 3,
 "labelType": 1
}
```
- Printing video

https://github.com/user-attachments/assets/1a810252-80f4-40c6-84fd-e08339215e2d

Out of curiosity, where can I see the commit for the delay you updated? I can't see any commit in https://gitee.mmote.ru/MultiMote/niimblue-nightly/commits/branch/master.

Thanks!

**Comment by MultiMote** [comment] 2024-08-21 11:07
My printer's properties match yours. Maybe your Bluetooth adapter is slower than mine.

> Out of curiosity, where can I see the commit for the delay you updated? I can't see any commit in

That repository is auto-committed every 24 hours (in current development phase). I made a commit, check it.

**Comment by MultiMote** [comment] 2024-08-23 12:58
@d4n1b there is no problems left? Can I close this issue?

**Comment by craftycram** [comment] 2024-08-24 22:16
I'm actually experiencing the same issue. I've been trying to get a working setup in Flutter/Dart and I currently have the same issue of the printer jittering at some point.  
As far as I can tell so far it's been happening since I changed the print start command from sending 1 to the uint16 quantity and the five zeros

**Comment by MultiMote** [comment] 2024-08-24 22:27
@craftycram there is a different formats of PrintStart in different protocol versions.

```
   |   1   |   2   |  3  |  4  |  5  |  6  |       7      |     8     |
   |       |       |     |     |     |     |              |           |
V1 |[  1  ]|       |     |     |     |     |              |           |
V3 |[ total_pages ]|     |     |     |     |              |           |
V4 |[ total_pages ]|[ 0 ]|[ 0 ]|[ 0 ]|[ 0 ]|[ page_color ]|           |
V5 |[ total_pages ]|[ 0 ]|[ 0 ]|[ 0 ]|[ 0 ]|[ page_color ]|[ quality ]|
```

B1 (in this issue) uses V4 as intended (according to the dumps and some reverse engineering). I don't think that's the problem.

**Comment by craftycram** [comment] 2024-08-24 22:31
Yea, I've been using V4 now, since I saw that you were using the V4 with the B1. Got the wrong protocol from another project first. Been trying with yours since, but didn't manage to get it working properly.

But I also can't reproduce the issue with your library.

**Comment by d4n1b** [comment] 2024-08-28 14:33
@MultiMote, sorry. I thought it was clear I was good with the approach increasing the waiting time as I attached a video successfully printing!

Happy to close. Thank again! :)

**Closed** 2024-08-28 14:35 UTC
Labels: bug
